# Personal Work
partitioning:
  data: ../data/raw/data_versions/ # ./data/raw/Doc3_Policy on Policy Management.docx
  strategy: hi_res
  extract_images: False
  infer_table: True
  chunking_strategy: by_title
  max_characters: 4000
  new_after_n_chars: 3800
  combine_text_under_n_chars: 2000
  image_output_dir_path: ../data/processed/figures/
  unittest_data_path: ../data/raw/data_unittest/

semantic_chunking:
  embedding_model: text-embedding-ada-002
  breakpoint_threshold_type: percentile
  breakpoint_threshold_amount: 95

chorma_db_local:
  collection_name: policy
  embedding_model: text-embedding-ada-002
  persist_directory: ../data/processed/dt_test/chroma_vector_db/

generation_model:
  temperature: 0
  azure_deployment: gpt-4-turbo
  openai_api_version: '2023-05-15'
  